# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake3

# The command to remove a file.
RM = /usr/bin/cmake3 -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/csmajs/znain001/lab-09-visitor-pattern-zaddy_lab09

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/csmajs/znain001/lab-09-visitor-pattern-zaddy_lab09

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake3 -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake3 -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake3 -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake3 -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake3 -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake3 -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake3 -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake3 -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/csmajs/znain001/lab-09-visitor-pattern-zaddy_lab09/CMakeFiles /home/csmajs/znain001/lab-09-visitor-pattern-zaddy_lab09/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/csmajs/znain001/lab-09-visitor-pattern-zaddy_lab09/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named lab

# Build rule for target.
lab: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lab
.PHONY : lab

# fast build rule for target.
lab/fast:
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/build
.PHONY : lab/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) -f googletest/googlemock/CMakeFiles/gmock_main.dir/build.make googletest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) -f googletest/googlemock/CMakeFiles/gmock.dir/build.make googletest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f googletest/googlemock/gtest/CMakeFiles/gtest_main.dir/build.make googletest/googlemock/gtest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f googletest/googlemock/gtest/CMakeFiles/gtest.dir/build.make googletest/googlemock/gtest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

ListContainer.o: ListContainer.cpp.o

.PHONY : ListContainer.o

# target to build an object file
ListContainer.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/ListContainer.cpp.o
.PHONY : ListContainer.cpp.o

ListContainer.i: ListContainer.cpp.i

.PHONY : ListContainer.i

# target to preprocess a source file
ListContainer.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/ListContainer.cpp.i
.PHONY : ListContainer.cpp.i

ListContainer.s: ListContainer.cpp.s

.PHONY : ListContainer.s

# target to generate assembly for a file
ListContainer.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/ListContainer.cpp.s
.PHONY : ListContainer.cpp.s

PrecisionFactory.o: PrecisionFactory.cpp.o

.PHONY : PrecisionFactory.o

# target to build an object file
PrecisionFactory.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/PrecisionFactory.cpp.o
.PHONY : PrecisionFactory.cpp.o

PrecisionFactory.i: PrecisionFactory.cpp.i

.PHONY : PrecisionFactory.i

# target to preprocess a source file
PrecisionFactory.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/PrecisionFactory.cpp.i
.PHONY : PrecisionFactory.cpp.i

PrecisionFactory.s: PrecisionFactory.cpp.s

.PHONY : PrecisionFactory.s

# target to generate assembly for a file
PrecisionFactory.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/PrecisionFactory.cpp.s
.PHONY : PrecisionFactory.cpp.s

PrecisionOp.o: PrecisionOp.cpp.o

.PHONY : PrecisionOp.o

# target to build an object file
PrecisionOp.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/PrecisionOp.cpp.o
.PHONY : PrecisionOp.cpp.o

PrecisionOp.i: PrecisionOp.cpp.i

.PHONY : PrecisionOp.i

# target to preprocess a source file
PrecisionOp.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/PrecisionOp.cpp.i
.PHONY : PrecisionOp.cpp.i

PrecisionOp.s: PrecisionOp.cpp.s

.PHONY : PrecisionOp.s

# target to generate assembly for a file
PrecisionOp.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/PrecisionOp.cpp.s
.PHONY : PrecisionOp.cpp.s

PrecisionRand.o: PrecisionRand.cpp.o

.PHONY : PrecisionRand.o

# target to build an object file
PrecisionRand.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/PrecisionRand.cpp.o
.PHONY : PrecisionRand.cpp.o

PrecisionRand.i: PrecisionRand.cpp.i

.PHONY : PrecisionRand.i

# target to preprocess a source file
PrecisionRand.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/PrecisionRand.cpp.i
.PHONY : PrecisionRand.cpp.i

PrecisionRand.s: PrecisionRand.cpp.s

.PHONY : PrecisionRand.s

# target to generate assembly for a file
PrecisionRand.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/PrecisionRand.cpp.s
.PHONY : PrecisionRand.cpp.s

SciOp.o: SciOp.cpp.o

.PHONY : SciOp.o

# target to build an object file
SciOp.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/SciOp.cpp.o
.PHONY : SciOp.cpp.o

SciOp.i: SciOp.cpp.i

.PHONY : SciOp.i

# target to preprocess a source file
SciOp.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/SciOp.cpp.i
.PHONY : SciOp.cpp.i

SciOp.s: SciOp.cpp.s

.PHONY : SciOp.s

# target to generate assembly for a file
SciOp.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/SciOp.cpp.s
.PHONY : SciOp.cpp.s

SciRand.o: SciRand.cpp.o

.PHONY : SciRand.o

# target to build an object file
SciRand.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/SciRand.cpp.o
.PHONY : SciRand.cpp.o

SciRand.i: SciRand.cpp.i

.PHONY : SciRand.i

# target to preprocess a source file
SciRand.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/SciRand.cpp.i
.PHONY : SciRand.cpp.i

SciRand.s: SciRand.cpp.s

.PHONY : SciRand.s

# target to generate assembly for a file
SciRand.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/SciRand.cpp.s
.PHONY : SciRand.cpp.s

ScientificFactory.o: ScientificFactory.cpp.o

.PHONY : ScientificFactory.o

# target to build an object file
ScientificFactory.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/ScientificFactory.cpp.o
.PHONY : ScientificFactory.cpp.o

ScientificFactory.i: ScientificFactory.cpp.i

.PHONY : ScientificFactory.i

# target to preprocess a source file
ScientificFactory.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/ScientificFactory.cpp.i
.PHONY : ScientificFactory.cpp.i

ScientificFactory.s: ScientificFactory.cpp.s

.PHONY : ScientificFactory.s

# target to generate assembly for a file
ScientificFactory.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/ScientificFactory.cpp.s
.PHONY : ScientificFactory.cpp.s

StandardDoubleFactory.o: StandardDoubleFactory.cpp.o

.PHONY : StandardDoubleFactory.o

# target to build an object file
StandardDoubleFactory.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/StandardDoubleFactory.cpp.o
.PHONY : StandardDoubleFactory.cpp.o

StandardDoubleFactory.i: StandardDoubleFactory.cpp.i

.PHONY : StandardDoubleFactory.i

# target to preprocess a source file
StandardDoubleFactory.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/StandardDoubleFactory.cpp.i
.PHONY : StandardDoubleFactory.cpp.i

StandardDoubleFactory.s: StandardDoubleFactory.cpp.s

.PHONY : StandardDoubleFactory.s

# target to generate assembly for a file
StandardDoubleFactory.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/StandardDoubleFactory.cpp.s
.PHONY : StandardDoubleFactory.cpp.s

VectorContainer.o: VectorContainer.cpp.o

.PHONY : VectorContainer.o

# target to build an object file
VectorContainer.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/VectorContainer.cpp.o
.PHONY : VectorContainer.cpp.o

VectorContainer.i: VectorContainer.cpp.i

.PHONY : VectorContainer.i

# target to preprocess a source file
VectorContainer.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/VectorContainer.cpp.i
.PHONY : VectorContainer.cpp.i

VectorContainer.s: VectorContainer.cpp.s

.PHONY : VectorContainer.s

# target to generate assembly for a file
VectorContainer.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/VectorContainer.cpp.s
.PHONY : VectorContainer.cpp.s

add.o: add.cpp.o

.PHONY : add.o

# target to build an object file
add.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/add.cpp.o
.PHONY : add.cpp.o

add.i: add.cpp.i

.PHONY : add.i

# target to preprocess a source file
add.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/add.cpp.i
.PHONY : add.cpp.i

add.s: add.cpp.s

.PHONY : add.s

# target to generate assembly for a file
add.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/add.cpp.s
.PHONY : add.cpp.s

decorator.o: decorator.cpp.o

.PHONY : decorator.o

# target to build an object file
decorator.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/decorator.cpp.o
.PHONY : decorator.cpp.o

decorator.i: decorator.cpp.i

.PHONY : decorator.i

# target to preprocess a source file
decorator.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/decorator.cpp.i
.PHONY : decorator.cpp.i

decorator.s: decorator.cpp.s

.PHONY : decorator.s

# target to generate assembly for a file
decorator.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/decorator.cpp.s
.PHONY : decorator.cpp.s

div.o: div.cpp.o

.PHONY : div.o

# target to build an object file
div.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/div.cpp.o
.PHONY : div.cpp.o

div.i: div.cpp.i

.PHONY : div.i

# target to preprocess a source file
div.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/div.cpp.i
.PHONY : div.cpp.i

div.s: div.cpp.s

.PHONY : div.s

# target to generate assembly for a file
div.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/div.cpp.s
.PHONY : div.cpp.s

iterator.o: iterator.cpp.o

.PHONY : iterator.o

# target to build an object file
iterator.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/iterator.cpp.o
.PHONY : iterator.cpp.o

iterator.i: iterator.cpp.i

.PHONY : iterator.i

# target to preprocess a source file
iterator.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/iterator.cpp.i
.PHONY : iterator.cpp.i

iterator.s: iterator.cpp.s

.PHONY : iterator.s

# target to generate assembly for a file
iterator.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/iterator.cpp.s
.PHONY : iterator.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/main.cpp.s
.PHONY : main.cpp.s

mult.o: mult.cpp.o

.PHONY : mult.o

# target to build an object file
mult.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/mult.cpp.o
.PHONY : mult.cpp.o

mult.i: mult.cpp.i

.PHONY : mult.i

# target to preprocess a source file
mult.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/mult.cpp.i
.PHONY : mult.cpp.i

mult.s: mult.cpp.s

.PHONY : mult.s

# target to generate assembly for a file
mult.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/mult.cpp.s
.PHONY : mult.cpp.s

op.o: op.cpp.o

.PHONY : op.o

# target to build an object file
op.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/op.cpp.o
.PHONY : op.cpp.o

op.i: op.cpp.i

.PHONY : op.i

# target to preprocess a source file
op.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/op.cpp.i
.PHONY : op.cpp.i

op.s: op.cpp.s

.PHONY : op.s

# target to generate assembly for a file
op.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/op.cpp.s
.PHONY : op.cpp.s

pow.o: pow.cpp.o

.PHONY : pow.o

# target to build an object file
pow.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/pow.cpp.o
.PHONY : pow.cpp.o

pow.i: pow.cpp.i

.PHONY : pow.i

# target to preprocess a source file
pow.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/pow.cpp.i
.PHONY : pow.cpp.i

pow.s: pow.cpp.s

.PHONY : pow.s

# target to generate assembly for a file
pow.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/pow.cpp.s
.PHONY : pow.cpp.s

rand.o: rand.cpp.o

.PHONY : rand.o

# target to build an object file
rand.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/rand.cpp.o
.PHONY : rand.cpp.o

rand.i: rand.cpp.i

.PHONY : rand.i

# target to preprocess a source file
rand.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/rand.cpp.i
.PHONY : rand.cpp.i

rand.s: rand.cpp.s

.PHONY : rand.s

# target to generate assembly for a file
rand.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/rand.cpp.s
.PHONY : rand.cpp.s

sort.o: sort.cpp.o

.PHONY : sort.o

# target to build an object file
sort.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/sort.cpp.o
.PHONY : sort.cpp.o

sort.i: sort.cpp.i

.PHONY : sort.i

# target to preprocess a source file
sort.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/sort.cpp.i
.PHONY : sort.cpp.i

sort.s: sort.cpp.s

.PHONY : sort.s

# target to generate assembly for a file
sort.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/sort.cpp.s
.PHONY : sort.cpp.s

sub.o: sub.cpp.o

.PHONY : sub.o

# target to build an object file
sub.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/sub.cpp.o
.PHONY : sub.cpp.o

sub.i: sub.cpp.i

.PHONY : sub.i

# target to preprocess a source file
sub.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/sub.cpp.i
.PHONY : sub.cpp.i

sub.s: sub.cpp.s

.PHONY : sub.s

# target to generate assembly for a file
sub.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/sub.cpp.s
.PHONY : sub.cpp.s

unit_test.o: unit_test.cpp.o

.PHONY : unit_test.o

# target to build an object file
unit_test.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/unit_test.cpp.o
.PHONY : unit_test.cpp.o

unit_test.i: unit_test.cpp.i

.PHONY : unit_test.i

# target to preprocess a source file
unit_test.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/unit_test.cpp.i
.PHONY : unit_test.cpp.i

unit_test.s: unit_test.cpp.s

.PHONY : unit_test.s

# target to generate assembly for a file
unit_test.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/unit_test.cpp.s
.PHONY : unit_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test"
	@echo "... lab"
	@echo "... gmock_main"
	@echo "... gmock"
	@echo "... gtest_main"
	@echo "... gtest"
	@echo "... ListContainer.o"
	@echo "... ListContainer.i"
	@echo "... ListContainer.s"
	@echo "... PrecisionFactory.o"
	@echo "... PrecisionFactory.i"
	@echo "... PrecisionFactory.s"
	@echo "... PrecisionOp.o"
	@echo "... PrecisionOp.i"
	@echo "... PrecisionOp.s"
	@echo "... PrecisionRand.o"
	@echo "... PrecisionRand.i"
	@echo "... PrecisionRand.s"
	@echo "... SciOp.o"
	@echo "... SciOp.i"
	@echo "... SciOp.s"
	@echo "... SciRand.o"
	@echo "... SciRand.i"
	@echo "... SciRand.s"
	@echo "... ScientificFactory.o"
	@echo "... ScientificFactory.i"
	@echo "... ScientificFactory.s"
	@echo "... StandardDoubleFactory.o"
	@echo "... StandardDoubleFactory.i"
	@echo "... StandardDoubleFactory.s"
	@echo "... VectorContainer.o"
	@echo "... VectorContainer.i"
	@echo "... VectorContainer.s"
	@echo "... add.o"
	@echo "... add.i"
	@echo "... add.s"
	@echo "... decorator.o"
	@echo "... decorator.i"
	@echo "... decorator.s"
	@echo "... div.o"
	@echo "... div.i"
	@echo "... div.s"
	@echo "... iterator.o"
	@echo "... iterator.i"
	@echo "... iterator.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mult.o"
	@echo "... mult.i"
	@echo "... mult.s"
	@echo "... op.o"
	@echo "... op.i"
	@echo "... op.s"
	@echo "... pow.o"
	@echo "... pow.i"
	@echo "... pow.s"
	@echo "... rand.o"
	@echo "... rand.i"
	@echo "... rand.s"
	@echo "... sort.o"
	@echo "... sort.i"
	@echo "... sort.s"
	@echo "... sub.o"
	@echo "... sub.i"
	@echo "... sub.s"
	@echo "... unit_test.o"
	@echo "... unit_test.i"
	@echo "... unit_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

